/**
 * Content icon options extracted from web/app/dev/styles/_icons.sass.
 * Values are the names consumed by web/components/base/Icon.jsx.
 */
export const ICON_OPTIONS = [
  '',
  'arrow-top-right',
  'arrow-right',
  'chevron-up',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'close',
  'menu-hamburger',
  'check',
  'view-more',
  'copy',
  'checklist',
  'clock',
  'mail',
  'phone',
  'world',
  'play',
  'download',
  'info',
  'search',
  'share',
  'book',
  'business',
  'pricing-tag',
  'flash',
  'pencil',
  'calendar',
  'pin-location',
  'pin-map',
  'key',
  'home',
  'shield',
  'diamond',
  'full-screen',
  'plug-and-play',
  'building',
  'globe',
  'instagram',
  'facebook',
  'twitter-x',
  'linkedin',
  'youtube',
  'tiktok',
  'whatsapp',
  'email',
  'threads',
  'briefcase-filled',
  'pin-filled',
  'pin-map-filled',
] as const;

export type IconOption = (typeof ICON_OPTIONS)[number];
