trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  tag: 'cms-$(Build.BuildId)'
  Uri: '329599622292.dkr.ecr.ap-southeast-3.amazonaws.com'
  RepositoryName: 'linknet/corporate-cms'
  awsCredentials: 'aws-iam-system-azure-devops-holdco-dev-corporate'

steps:
- checkout: self

# BUILD DOCKER
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    Dockerfile: $(System.DefaultWorkingDirectory)/Dockerfile
    buildContext: $(System.DefaultWorkingDirectory)
    repository: $(Uri)/$(RepositoryName)
    tags: |
      $(tag)

# PUSH IMAGE
- task: ECRPushImage@1
  displayName: 'Push Docker Image'
  condition: succeeded()
  inputs:
    awsCredentials: $(awsCredentials)
    regionName: ap-southeast-3
    imageSource: 'imagename'
    sourceImageName: $(Uri)/$(RepositoryName)
    sourceImageTag: $(tag)
    pushTag: $(tag)
    repositoryName: $(RepositoryName)
    autoCreateRepository: true

# MSDO SCAN
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps Scan'
  condition: always()
  inputs:
    command: 'run'
    policy: 'azuredevops'
    tools: 'checkov, templateanalyzer'
    publish: true
    artifactName: 'CodeAnalysisLogs'

# PUBLISH ARTIFACTS
- task: PublishBuildArtifacts@1
  displayName: 'Publish Security Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'security-reports'