-- Generated by scripts/db-rebuild/generate-rebuild-artifacts.cjs
-- Purpose: import audited legacy_raw data into the Prisma-compatible public schema.
-- Run this only after baseline Prisma migration has created an empty public schema.

BEGIN;

DO $$
DECLARE
  target_table text;
  existing_rows bigint;
BEGIN
  IF lower(coalesce(current_setting('legacy_rebuild.allow_import', true), '')) <> 'true' THEN
    RAISE EXCEPTION 'Refusing canonical legacy import. Run only on local/staging and set legacy_rebuild.allow_import=true for this session.';
  END IF;

  IF current_database() ~* '(prod|production)' THEN
    RAISE EXCEPTION 'Refusing to import into a database whose name looks like production: %', current_database();
  END IF;

  IF to_regnamespace('legacy_raw') IS NULL THEN
    RAISE EXCEPTION 'legacy_raw schema is missing. Run linknet_bersih_legacy_raw.postgres.sql first.';
  END IF;

  FOREACH target_table IN ARRAY ARRAY['announcement_types', 'announcement_sections', 'announcements', 'awards', 'career_content', 'contact_us', 'management_categories', 'managements', 'menus', 'news_categories', 'news', 'news_highlights', 'permissions', 'report_types', 'report_sections', 'reports', 'roles', 'role_permissions', 'url_redirects', 'users', 'user_roles'] LOOP
    IF to_regclass(format('public.%I', target_table)) IS NULL THEN
      RAISE EXCEPTION 'Expected target table public.% does not exist. Run Prisma baseline migration first.', target_table;
    END IF;

    EXECUTE format('SELECT count(*) FROM public.%I', target_table) INTO existing_rows;
    IF existing_rows > 0 THEN
      RAISE EXCEPTION 'Refusing import because public.% already has % row(s). Use a fresh local/staging database.', target_table, existing_rows;
    END IF;
  END LOOP;

  IF NOT EXISTS (SELECT 1 FROM legacy_raw.users LIMIT 1) THEN
    RAISE EXCEPTION 'Legacy users table is empty; news import requires a fallback created_by_id user.';
  END IF;
END $$;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION legacy_raw.slugify(value text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT trim(both '-' from regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', '-', 'g'));
$$;

CREATE OR REPLACE FUNCTION legacy_raw.is_valid_jsonb(value text)
RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  IF value IS NULL OR btrim(value) = '' THEN
    RETURN true;
  END IF;
  PERFORM value::jsonb;
  RETURN true;
EXCEPTION WHEN others THEN
  RETURN false;
END;
$$;

CREATE TABLE IF NOT EXISTS legacy_raw.legacy_import_mappings (
  source_table text NOT NULL,
  old_id text NOT NULL,
  target_table text NOT NULL,
  new_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source_table, old_id)
);

CREATE TABLE IF NOT EXISTS legacy_raw.legacy_import_skipped_rows (
  source_table text NOT NULL,
  old_id text NOT NULL,
  target_table text NOT NULL,
  reason text NOT NULL,
  payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

DO $$
DECLARE
  invalid_count bigint;
BEGIN
  SELECT count(*) INTO invalid_count
  FROM legacy_raw.legacy_import_mappings;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'legacy_raw.legacy_import_mappings already has % row(s). Use a fresh local/staging database.', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.menus m
  LEFT JOIN legacy_raw.menus p ON p.id = m.parent_id
  WHERE m.parent_id IS NOT NULL AND p.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Menu parent orphan detected: % row(s). Stop and inspect legacy_raw.menus.', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.menus
  WHERE NOT legacy_raw.is_valid_jsonb(translations);
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Invalid JSON detected in legacy_raw.menus.translations: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.managements m
  LEFT JOIN legacy_raw.management_categories c ON c.id = m.category_id
  WHERE m.category_id IS NULL OR c.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Management category missing/orphan detected: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.report_sections s
  LEFT JOIN legacy_raw.report_types t ON t.id = s.report_type_id
  WHERE t.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Report section type orphan detected: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.report_items i
  LEFT JOIN legacy_raw.report_types t ON t.id = i.report_type_id
  WHERE i.report_type_id IS NOT NULL AND t.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Report item type orphan detected: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.report_items i
  LEFT JOIN legacy_raw.report_sections s ON s.id = i.report_section_id
  WHERE i.report_section_id IS NOT NULL AND s.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Report item section orphan detected: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.announcement_sections s
  LEFT JOIN legacy_raw.announcement_types t ON t.id = s.announcement_type_id
  WHERE t.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Announcement section type orphan detected: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.announcement_items i
  LEFT JOIN legacy_raw.announcement_types t ON t.id = i.announcement_type_id
  WHERE i.announcement_type_id IS NOT NULL AND t.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Announcement item type orphan detected: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.announcement_items i
  LEFT JOIN legacy_raw.announcement_sections s ON s.id = i.announcement_section_id
  WHERE i.announcement_section_id IS NOT NULL AND s.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Announcement item section orphan detected: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.news_content n
  LEFT JOIN legacy_raw.news_category c ON c.id = n.id_category
  WHERE n.id_category IS NULL OR c.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'News category missing/orphan detected: % row(s).', invalid_count;
  END IF;

  SELECT count(*) INTO invalid_count
  FROM legacy_raw.news_highlight h
  LEFT JOIN legacy_raw.news_content n ON n.id = h.id_news
  WHERE n.id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'News highlight orphan detected: % row(s).', invalid_count;
  END IF;
END $$;

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'announcement_items', id::text, 'announcements', gen_random_uuid()::text
FROM legacy_raw."announcement_items";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'announcement_sections', id::text, 'announcement_sections', gen_random_uuid()::text
FROM legacy_raw."announcement_sections";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'announcement_types', id::text, 'announcement_types', gen_random_uuid()::text
FROM legacy_raw."announcement_types";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'awards', id::text, 'awards', gen_random_uuid()::text
FROM legacy_raw."awards";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'contact_us', id::text, 'contact_us', gen_random_uuid()::text
FROM legacy_raw."contact_us";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'management_categories', id::text, 'management_categories', gen_random_uuid()::text
FROM legacy_raw."management_categories";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'managements', id::text, 'managements', gen_random_uuid()::text
FROM legacy_raw."managements";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'news_category', id::text, 'news_categories', gen_random_uuid()::text
FROM legacy_raw."news_category";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'news_content', id::text, 'news', gen_random_uuid()::text
FROM legacy_raw."news_content";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'news_highlight', id::text, 'news_highlights', gen_random_uuid()::text
FROM legacy_raw."news_highlight";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'permissions', id::text, 'permissions', gen_random_uuid()::text
FROM legacy_raw."permissions";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'report_items', id::text, 'reports', gen_random_uuid()::text
FROM legacy_raw."report_items";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'report_sections', id::text, 'report_sections', gen_random_uuid()::text
FROM legacy_raw."report_sections";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'report_types', id::text, 'report_types', gen_random_uuid()::text
FROM legacy_raw."report_types";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'roles', id::text, 'roles', gen_random_uuid()::text
FROM legacy_raw."roles";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'role_permission', id::text, 'role_permissions', gen_random_uuid()::text
FROM legacy_raw."role_permission";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'tb_url_redirect', id::text, 'url_redirects', gen_random_uuid()::text
FROM legacy_raw."tb_url_redirect";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'users', id::text, 'users', gen_random_uuid()::text
FROM legacy_raw."users";

INSERT INTO legacy_raw.legacy_import_mappings (source_table, old_id, target_table, new_id)
SELECT 'user_role', id::text, 'user_roles', gen_random_uuid()::text
FROM legacy_raw."user_role";

INSERT INTO public.roles (id, name, slug, description, is_system, created_at, updated_at, deleted_at)
WITH src AS (
  SELECT r.*,
         count(*) OVER (PARTITION BY lower(r.name)) AS duplicate_names
  FROM legacy_raw.roles r
)
SELECT map.new_id,
       CASE WHEN src.duplicate_names > 1 THEN src.name || ' #' || src.id::text ELSE src.name END,
       legacy_raw.slugify(src.name || '-' || src.id::text),
       'Imported from MySQL backup role id ' || src.id::text,
       lower(src.name) LIKE '%admin%',
       coalesce(src.created_at, now()),
       coalesce(src.updated_at, src.created_at, now()),
       NULL
FROM src
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'roles' AND map.old_id = src.id::text;

INSERT INTO public.permissions (id, name, slug, module, description, created_at, updated_at)
WITH src AS (
  SELECT p.*,
         count(*) OVER (PARTITION BY lower(p.name)) AS duplicate_names
  FROM legacy_raw.permissions p
)
SELECT map.new_id,
       CASE WHEN src.duplicate_names > 1 THEN src.name || ' #' || src.id::text ELSE src.name END,
       legacy_raw.slugify(coalesce(src.module, 'legacy') || '-' || src.name || '-' || src.id::text),
       coalesce(nullif(src.module, ''), 'legacy'),
       'Imported from MySQL backup permission id ' || src.id::text,
       coalesce(src.created_at, now()),
       coalesce(src.updated_at, src.created_at, now())
FROM src
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'permissions' AND map.old_id = src.id::text;

INSERT INTO public.users (
  id, email, username, password, first_name, last_name, avatar, phone, status,
  email_verified_at, last_login_at, failed_login_attempts, locked_at, locked_reason,
  password_changed_at, must_change_password, mfa_enabled, mfa_secret, mfa_verified_at,
  created_at, updated_at, deleted_at
)
SELECT map.new_id,
       u.email,
       legacy_raw.slugify(split_part(u.email, '@', 1) || '-' || u.id::text),
       CASE
         WHEN u.password LIKE '$2y$%' THEN '$2b$' || substr(u.password, 5)
         ELSE u.password
       END,
       coalesce(nullif(split_part(u.name, ' ', 1), ''), u.name),
       coalesce(nullif(trim(substr(u.name, length(split_part(u.name, ' ', 1)) + 1)), ''), ''),
       coalesce(u.avatar, u.img_user),
       NULL,
       CASE WHEN coalesce(u.data_status, 0) = 1 THEN 'ACTIVE'::"UserStatus" ELSE 'INACTIVE'::"UserStatus" END,
       u.email_verified_at,
       NULL,
       0,
       NULL,
       NULL,
       coalesce(u.updated_at, u.created_at, now()),
       false,
       false,
       NULL,
       NULL,
       coalesce(u.created_at, now()),
       coalesce(u.updated_at, u.created_at, now()),
       u.deleted_at
FROM legacy_raw.users u
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'users' AND map.old_id = u.id::text;

INSERT INTO public.role_permissions (id, role_id, permission_id, created_at)
SELECT rp_map.new_id, role_map.new_id, permission_map.new_id, now()
FROM legacy_raw.role_permission rp
JOIN legacy_raw.legacy_import_mappings rp_map
  ON rp_map.source_table = 'role_permission' AND rp_map.old_id = rp.id::text
JOIN legacy_raw.legacy_import_mappings role_map
  ON role_map.source_table = 'roles' AND role_map.old_id = rp.role_id::text
JOIN legacy_raw.legacy_import_mappings permission_map
  ON permission_map.source_table = 'permissions' AND permission_map.old_id = rp.permission_id::text;

INSERT INTO legacy_raw.legacy_import_skipped_rows (source_table, old_id, target_table, reason, payload)
SELECT 'role_permission',
       rp.id::text,
       'role_permissions',
       concat_ws('; ',
         CASE WHEN r.id IS NULL THEN 'missing legacy role_id ' || rp.role_id::text END,
         CASE WHEN p.id IS NULL THEN 'missing legacy permission_id ' || rp.permission_id::text END
       ),
       to_jsonb(rp)
FROM legacy_raw.role_permission rp
LEFT JOIN legacy_raw.roles r ON r.id = rp.role_id
LEFT JOIN legacy_raw.permissions p ON p.id = rp.permission_id
WHERE r.id IS NULL OR p.id IS NULL;

INSERT INTO public.user_roles (id, user_id, role_id, created_at)
SELECT ur_map.new_id, user_map.new_id, role_map.new_id, now()
FROM legacy_raw.user_role ur
JOIN legacy_raw.legacy_import_mappings ur_map
  ON ur_map.source_table = 'user_role' AND ur_map.old_id = ur.id::text
JOIN legacy_raw.legacy_import_mappings user_map
  ON user_map.source_table = 'users' AND user_map.old_id = ur.user_id::text
JOIN legacy_raw.legacy_import_mappings role_map
  ON role_map.source_table = 'roles' AND role_map.old_id = ur.role_id::text;

INSERT INTO legacy_raw.legacy_import_skipped_rows (source_table, old_id, target_table, reason, payload)
SELECT 'user_role',
       ur.id::text,
       'user_roles',
       concat_ws('; ',
         CASE WHEN u.id IS NULL THEN 'missing legacy user_id ' || ur.user_id::text END,
         CASE WHEN r.id IS NULL THEN 'missing legacy role_id ' || ur.role_id::text END
       ),
       to_jsonb(ur)
FROM legacy_raw.user_role ur
LEFT JOIN legacy_raw.users u ON u.id = ur.user_id
LEFT JOIN legacy_raw.roles r ON r.id = ur.role_id
WHERE u.id IS NULL OR r.id IS NULL;

INSERT INTO public.menus (
  id, parent_id, section_title, section_order, title, translations, slug, url, icon, image,
  description, badge, position, type, "order", is_active, open_new_tab, css_class,
  created_by, updated_by, created_at, updated_at
)
SELECT id,
       parent_id,
       section_title,
       coalesce(section_order, 0),
       title,
       CASE WHEN translations IS NULL OR btrim(translations) = '' THEN NULL ELSE translations::jsonb END,
       slug,
       url,
       icon,
       image,
       description,
       badge,
       lower(btrim(coalesce(position, 'header')))::"MenuPosition",
       lower(btrim(coalesce(type, 'link')))::"MenuType",
       coalesce("order", 0),
       coalesce(is_active, true),
       coalesce(open_new_tab, false),
       css_class,
       created_by,
       updated_by,
       created_at,
       updated_at
FROM legacy_raw.menus;

INSERT INTO public.career_content (
  id, position, slug, division, type, link_job, location, description, description_id,
  requirements, requirements_id, status, expiry_date, created_at, updated_at, created_by, updated_by
)
SELECT id, position, slug, division, type, link_job, location, description, description_id,
       requirements, requirements_id, coalesce(status, 'active'), expiry_date, created_at, updated_at,
       created_by, updated_by
FROM legacy_raw.career_content;

INSERT INTO public.management_categories (
  id, name, slug, description, position, is_active, created_by, updated_by, created_at, updated_at, deleted_at
)
WITH src AS (
  SELECT c.*,
         legacy_raw.slugify(coalesce(nullif(c.slug, ''), c.name)) AS base_slug,
         count(*) OVER (PARTITION BY legacy_raw.slugify(coalesce(nullif(c.slug, ''), c.name))) AS duplicate_slugs
  FROM legacy_raw.management_categories c
)
SELECT map.new_id,
       src.name,
       CASE WHEN src.duplicate_slugs > 1 THEN src.base_slug || '-' || src.id::text ELSE src.base_slug END,
       src.description,
       coalesce(src."order", 0),
       coalesce(src.status, 1) = 1,
       src.created_by,
       src.updated_by,
       coalesce(src.created_at, now()),
       coalesce(src.updated_at, src.created_at, now()),
       NULL
FROM src
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'management_categories' AND map.old_id = src.id::text;

INSERT INTO public.managements (
  id, category_id, name, slug, position_en, position_id, description, photo, bio_en, bio_id,
  email, phone, linkedin, "order", is_active, created_by, updated_by, created_at, updated_at, deleted_at
)
WITH src AS (
  SELECT m.*,
         legacy_raw.slugify(m.name || '-' || m.id::text) AS generated_slug
  FROM legacy_raw.managements m
)
SELECT management_map.new_id,
       category_map.new_id,
       src.name,
       src.generated_slug,
       src.position_en,
       src.position_id,
       src.category,
       src.photo,
       src.bio_en,
       src.bio_id,
       NULL,
       NULL,
       NULL,
       coalesce(src.data_order, 0),
       coalesce(src.data_status, 1) = 1,
       src.created_by,
       src.updated_by,
       coalesce(src.created_at, now()),
       coalesce(src.updated_at, src.created_at, now()),
       NULL
FROM src
JOIN legacy_raw.legacy_import_mappings management_map
  ON management_map.source_table = 'managements' AND management_map.old_id = src.id::text
LEFT JOIN legacy_raw.legacy_import_mappings category_map
  ON category_map.source_table = 'management_categories' AND category_map.old_id = src.category_id::text
WHERE src.category_id IS NOT NULL;

INSERT INTO public.awards (
  id, title, title_id, title_en, slug, description, description_id, description_en, top_logo,
  image, link, issuer, year, issue_date, position, is_active, status, created_by, updated_by,
  created_at, updated_at, deleted_at
)
SELECT map.new_id,
       coalesce(a.nama_awards, a.nama_awards_en, a.nama_awards_id, 'Award ' || a.id::text),
       a.nama_awards_id,
       a.nama_awards_en,
       legacy_raw.slugify(coalesce(a.nama_awards, a.nama_awards_en, a.nama_awards_id, 'award') || '-' || extract(year from a.tahun)::int::text || '-' || a.id::text),
       a.detail_awards,
       a.detail_awards_id,
       a.detail_awards_en,
       NULL,
       a.image,
       a.link,
       'Link Net',
       extract(year from a.tahun)::int,
       a.tahun::timestamp,
       a.id::integer,
       true,
       'ACTIVE',
       a.created_by::text,
       a.updated_by::text,
       coalesce(a.created_at, now()),
       coalesce(a.updated_at, a.created_at, now()),
       NULL
FROM legacy_raw.awards a
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'awards' AND map.old_id = a.id::text;

INSERT INTO public.contact_us (
  id, first_name, last_name, email, phone, role, company, inquiry_type, subject, message,
  status, ip_address, user_agent, read_at, submitted_at, created_at, updated_at
)
SELECT map.new_id,
       c.first_name,
       c.last_name,
       c.email,
       c.phone,
       c.role,
       c.company,
       CASE
         WHEN upper(c.inquiry_type) IN ('BUSINESS', 'SUPPORT', 'CAREER', 'OTHERS')
           THEN upper(c.inquiry_type)::"InquiryType"
         ELSE 'OTHERS'::"InquiryType"
       END,
       'Legacy contact import',
       c.message,
       'NEW'::"ContactStatus",
       c.ip_address,
       c.user_agent,
       NULL,
       coalesce(c.submitted_at, c.created_at, now()),
       coalesce(c.created_at, c.submitted_at, now()),
       coalesce(c.updated_at, c.created_at, c.submitted_at, now())
FROM legacy_raw.contact_us c
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'contact_us' AND map.old_id = c.id::text;

INSERT INTO public.announcement_types (
  id, name, slug, type, description, icon, color, position, is_active, created_at, updated_at, deleted_at
)
SELECT map.new_id,
       t.name,
       legacy_raw.slugify(t.name || '-' || t.id::text),
       coalesce(t.type, 'List'),
       NULL,
       NULL,
       NULL,
       coalesce(t.sort_order, 0),
       coalesce(t.is_active, true),
       coalesce(t.created_at, now()),
       coalesce(t.updated_at, t.created_at, now()),
       t.deleted_at
FROM legacy_raw.announcement_types t
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'announcement_types' AND map.old_id = t.id::text;

INSERT INTO public.announcement_sections (
  id, type_id, name, slug, description, announcement_year, cta_enabled, cta_text, cta_url,
  position, is_active, created_at, updated_at, deleted_at
)
SELECT section_map.new_id,
       type_map.new_id,
       s.title,
       legacy_raw.slugify(s.title || '-' || s.id::text),
       s.description,
       s.announcement_year,
       coalesce(s.cta_enabled, false),
       s.cta_text,
       s.cta_url,
       coalesce(s.sort_order, 0),
       coalesce(s.is_active, true),
       coalesce(s.created_at, now()),
       coalesce(s.updated_at, s.created_at, now()),
       s.deleted_at
FROM legacy_raw.announcement_sections s
JOIN legacy_raw.legacy_import_mappings section_map
  ON section_map.source_table = 'announcement_sections' AND section_map.old_id = s.id::text
JOIN legacy_raw.legacy_import_mappings type_map
  ON type_map.source_table = 'announcement_types' AND type_map.old_id = s.announcement_type_id::text;

INSERT INTO public.announcements (
  id, type_id, section_id, title, slug, description, pdf_file, cover_image, data_type,
  audit_status, file_size, sort_order, is_active, status, created_at, updated_at, deleted_at
)
SELECT item_map.new_id,
       type_map.new_id,
       section_map.new_id,
       i.title,
       legacy_raw.slugify(i.title || '-' || i.id::text),
       i.sub_description,
       i.pdf_file,
       i.cover_image,
       i.data_type,
       i.audit_status,
       i.file_size,
       coalesce(i.sort_order, 0),
       coalesce(i.is_active, true),
       CASE WHEN coalesce(i.is_active, true) THEN 'PUBLISHED'::"ContentStatus" ELSE 'ARCHIVED'::"ContentStatus" END,
       coalesce(i.created_at, now()),
       coalesce(i.updated_at, i.created_at, now()),
       i.deleted_at
FROM legacy_raw.announcement_items i
JOIN legacy_raw.legacy_import_mappings item_map
  ON item_map.source_table = 'announcement_items' AND item_map.old_id = i.id::text
LEFT JOIN legacy_raw.legacy_import_mappings type_map
  ON type_map.source_table = 'announcement_types' AND type_map.old_id = i.announcement_type_id::text
LEFT JOIN legacy_raw.legacy_import_mappings section_map
  ON section_map.source_table = 'announcement_sections' AND section_map.old_id = i.announcement_section_id::text;

INSERT INTO public.report_types (
  id, name, slug, description, icon, color, position, is_active, created_at, updated_at, deleted_at
)
SELECT map.new_id,
       t.name,
       legacy_raw.slugify(t.name || '-' || t.id::text),
       NULL,
       NULL,
       NULL,
       coalesce(t.sort_order, 0),
       coalesce(t.is_active, true),
       coalesce(t.created_at, now()),
       coalesce(t.updated_at, t.created_at, now()),
       t.deleted_at
FROM legacy_raw.report_types t
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'report_types' AND map.old_id = t.id::text;

INSERT INTO public.report_sections (
  id, type_id, name, slug, description, position, is_active, created_at, updated_at, deleted_at
)
SELECT section_map.new_id,
       type_map.new_id,
       s.title,
       legacy_raw.slugify(s.title || '-' || s.id::text),
       s.description,
       coalesce(s.sort_order, 0),
       coalesce(s.is_active, true),
       coalesce(s.created_at, now()),
       coalesce(s.updated_at, s.created_at, now()),
       s.deleted_at
FROM legacy_raw.report_sections s
JOIN legacy_raw.legacy_import_mappings section_map
  ON section_map.source_table = 'report_sections' AND section_map.old_id = s.id::text
JOIN legacy_raw.legacy_import_mappings type_map
  ON type_map.source_table = 'report_types' AND type_map.old_id = s.report_type_id::text;

INSERT INTO public.reports (
  id, type_id, section_id, title, slug, description, pdf_file, cover_image, data_type,
  audit_status, file_size, sort_order, is_active, period, year, quarter, file_url, file_type,
  thumbnail, downloads, status, published_at, created_at, updated_at, deleted_at
)
SELECT item_map.new_id,
       type_map.new_id,
       section_map.new_id,
       i.title,
       legacy_raw.slugify(i.title || '-' || i.id::text),
       i.sub_description,
       i.pdf_file,
       i.cover_image,
       i.data_type,
       i.audit_status,
       i.file_size,
       coalesce(i.sort_order, 0),
       coalesce(i.is_active, true),
       NULL,
       s.report_year,
       NULL,
       i.pdf_file,
       NULL,
       i.cover_image,
       0,
       CASE WHEN coalesce(i.is_active, true) THEN 'PUBLISHED'::"ContentStatus" ELSE 'ARCHIVED'::"ContentStatus" END,
       CASE WHEN coalesce(i.is_active, true) THEN coalesce(i.created_at, now()) ELSE NULL END,
       coalesce(i.created_at, now()),
       coalesce(i.updated_at, i.created_at, now()),
       i.deleted_at
FROM legacy_raw.report_items i
LEFT JOIN legacy_raw.report_sections s ON s.id = i.report_section_id
JOIN legacy_raw.legacy_import_mappings item_map
  ON item_map.source_table = 'report_items' AND item_map.old_id = i.id::text
LEFT JOIN legacy_raw.legacy_import_mappings type_map
  ON type_map.source_table = 'report_types' AND type_map.old_id = i.report_type_id::text
LEFT JOIN legacy_raw.legacy_import_mappings section_map
  ON section_map.source_table = 'report_sections' AND section_map.old_id = i.report_section_id::text;

INSERT INTO public.news_categories (
  id, name_en, name_id, slug, description, position, is_active, created_by, updated_by, created_at, updated_at, deleted_at
)
WITH src AS (
  SELECT c.*,
         legacy_raw.slugify(coalesce(nullif(c.slug, ''), c.category_name)) AS base_slug,
         count(*) OVER (PARTITION BY legacy_raw.slugify(coalesce(nullif(c.slug, ''), c.category_name))) AS duplicate_slugs
  FROM legacy_raw.news_category c
)
SELECT map.new_id,
       src.category_name,
       src.category_name,
       CASE WHEN src.duplicate_slugs > 1 THEN src.base_slug || '-' || src.id::text ELSE src.base_slug END,
       NULL,
       coalesce(src.data_order, 0),
       coalesce(src.data_status, true),
       src.created_by,
       src.updated_by,
       coalesce(src.created_at, now()),
       coalesce(src.updated_at, src.created_at, now()),
       NULL
FROM src
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'news_category' AND map.old_id = src.id::text;

INSERT INTO public.news (
  id, title_en, title_id, slug, news_date, news_thumbnail, excerpt_en, excerpt_id,
  content_en, content_id, news_link, author, meta_title, meta_description, meta_desc,
  category_id, meta_keywords, custom_css, custom_js, view_count, view_count_unique,
  status, visibility, published_at, created_by_id, updated_by_id, created_at, updated_at, deleted_at
)
SELECT news_map.new_id,
       n.title_en,
       n.title_id,
       legacy_raw.slugify(coalesce(nullif(n.slug, ''), n.title_en) || '-' || n.id::text),
       coalesce(n.news_date, n.created_at::date, current_date),
       n.news_thumbnail,
       n.excerpt_en,
       n.excerpt_id,
       n.content_en,
       n.content_id,
       n.news_link,
       n.author,
       n.title_en,
       n.meta_desc,
       n.meta_desc,
       category_map.new_id,
       n.meta_keyword,
       n.custom_css,
       n.custom_js,
       least(coalesce(n.view_count, 0), 2147483647)::integer,
       least(coalesce(n.view_count_unique, 0), 2147483647)::integer,
       CASE WHEN coalesce(n.data_status, true) THEN 'PUBLISHED'::"ContentStatus" ELSE 'DRAFT'::"ContentStatus" END,
       'PUBLIC',
       CASE WHEN coalesce(n.data_status, true) THEN coalesce(n.news_date::timestamp, n.created_at, now()) ELSE NULL END,
       coalesce(publisher_map.new_id, first_user.new_id),
       updater_map.new_id,
       coalesce(n.created_at, now()),
       coalesce(n.updated_at, n.created_at, now()),
       NULL
FROM legacy_raw.news_content n
JOIN legacy_raw.legacy_import_mappings news_map
  ON news_map.source_table = 'news_content' AND news_map.old_id = n.id::text
JOIN legacy_raw.legacy_import_mappings category_map
  ON category_map.source_table = 'news_category' AND category_map.old_id = n.id_category::text
CROSS JOIN LATERAL (
  SELECT new_id
  FROM legacy_raw.legacy_import_mappings
  WHERE source_table = 'users'
  ORDER BY old_id::bigint
  LIMIT 1
) first_user
LEFT JOIN legacy_raw.legacy_import_mappings publisher_map
  ON publisher_map.source_table = 'users' AND publisher_map.old_id = n.id_publisher::text
LEFT JOIN legacy_raw.legacy_import_mappings updater_map
  ON updater_map.source_table = 'users' AND updater_map.old_id = n.updated_by;

INSERT INTO public.news_highlights (id, news_id, position, created_by, updated_by, created_at, updated_at)
SELECT highlight_map.new_id,
       news_map.new_id,
       coalesce(h.data_order, h.id)::integer,
       h.created_by,
       h.updated_by,
       coalesce(h.created_at, now()),
       coalesce(h.updated_at, h.created_at, now())
FROM legacy_raw.news_highlight h
JOIN legacy_raw.legacy_import_mappings highlight_map
  ON highlight_map.source_table = 'news_highlight' AND highlight_map.old_id = h.id::text
JOIN legacy_raw.legacy_import_mappings news_map
  ON news_map.source_table = 'news_content' AND news_map.old_id = h.id_news::text;

INSERT INTO public.url_redirects (
  id, from_url, to_url, status_code, hits, is_active, created_at, updated_at, deleted_at
)
SELECT map.new_id,
       r.source_path,
       r.url_destination,
       301,
       0,
       true,
       coalesce(r.created_at, now()),
       coalesce(r.updated_at, r.created_at, now()),
       NULL
FROM legacy_raw.tb_url_redirect r
JOIN legacy_raw.legacy_import_mappings map
  ON map.source_table = 'tb_url_redirect' AND map.old_id = r.id::text;

SELECT setval(pg_get_serial_sequence('public.menus', 'id'), coalesce((SELECT max(id) FROM public.menus), 1), (SELECT count(*) > 0 FROM public.menus));
SELECT setval(pg_get_serial_sequence('public.career_content', 'id'), coalesce((SELECT max(id) FROM public.career_content), 1), (SELECT count(*) > 0 FROM public.career_content));

COMMIT;
