-- Generated by scripts/db-rebuild/generate-rebuild-artifacts.cjs
-- Purpose: read-only row count checks after raw and canonical imports.

WITH raw_counts AS (
SELECT 'announcement_items' AS table_name, 478::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."announcement_items"
UNION ALL
SELECT 'announcement_sections' AS table_name, 40::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."announcement_sections"
UNION ALL
SELECT 'announcement_types' AS table_name, 3::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."announcement_types"
UNION ALL
SELECT 'awards' AS table_name, 20::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."awards"
UNION ALL
SELECT 'career_content' AS table_name, 51::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."career_content"
UNION ALL
SELECT 'contact_us' AS table_name, 114::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."contact_us"
UNION ALL
SELECT 'managements' AS table_name, 24::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."managements"
UNION ALL
SELECT 'management_categories' AS table_name, 6::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."management_categories"
UNION ALL
SELECT 'menus' AS table_name, 58::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."menus"
UNION ALL
SELECT 'news_category' AS table_name, 9::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."news_category"
UNION ALL
SELECT 'news_content' AS table_name, 71::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."news_content"
UNION ALL
SELECT 'news_highlight' AS table_name, 4::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."news_highlight"
UNION ALL
SELECT 'permissions' AS table_name, 51::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."permissions"
UNION ALL
SELECT 'report_items' AS table_name, 65::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."report_items"
UNION ALL
SELECT 'report_sections' AS table_name, 13::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."report_sections"
UNION ALL
SELECT 'report_types' AS table_name, 3::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."report_types"
UNION ALL
SELECT 'roles' AS table_name, 3::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."roles"
UNION ALL
SELECT 'role_permission' AS table_name, 208::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."role_permission"
UNION ALL
SELECT 'tb_url_redirect' AS table_name, 1::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."tb_url_redirect"
UNION ALL
SELECT 'users' AS table_name, 4::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."users"
UNION ALL
SELECT 'user_role' AS table_name, 9::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM legacy_raw."user_role"
)
SELECT table_name,
       expected_rows,
       actual_rows,
       CASE WHEN expected_rows = actual_rows THEN 'OK' ELSE 'MISMATCH' END AS status
FROM raw_counts
ORDER BY table_name;

WITH canonical_counts AS (
SELECT 'announcement_types' AS source_table, 'announcement_types' AS target_table, 3::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."announcement_types"
UNION ALL
SELECT 'announcement_sections' AS source_table, 'announcement_sections' AS target_table, 40::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."announcement_sections"
UNION ALL
SELECT 'announcement_items' AS source_table, 'announcements' AS target_table, 478::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."announcements"
UNION ALL
SELECT 'awards' AS source_table, 'awards' AS target_table, 20::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."awards"
UNION ALL
SELECT 'career_content' AS source_table, 'career_content' AS target_table, 51::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."career_content"
UNION ALL
SELECT 'contact_us' AS source_table, 'contact_us' AS target_table, 114::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."contact_us"
UNION ALL
SELECT 'management_categories' AS source_table, 'management_categories' AS target_table, 6::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."management_categories"
UNION ALL
SELECT 'managements' AS source_table, 'managements' AS target_table, 24::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."managements"
UNION ALL
SELECT 'menus' AS source_table, 'menus' AS target_table, 58::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."menus"
UNION ALL
SELECT 'news_category' AS source_table, 'news_categories' AS target_table, 9::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."news_categories"
UNION ALL
SELECT 'news_content' AS source_table, 'news' AS target_table, 71::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."news"
UNION ALL
SELECT 'news_highlight' AS source_table, 'news_highlights' AS target_table, 4::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."news_highlights"
UNION ALL
SELECT 'permissions' AS source_table, 'permissions' AS target_table, 51::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."permissions"
UNION ALL
SELECT 'report_types' AS source_table, 'report_types' AS target_table, 3::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."report_types"
UNION ALL
SELECT 'report_sections' AS source_table, 'report_sections' AS target_table, 13::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."report_sections"
UNION ALL
SELECT 'report_items' AS source_table, 'reports' AS target_table, 65::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."reports"
UNION ALL
SELECT 'roles' AS source_table, 'roles' AS target_table, 3::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."roles"
UNION ALL
SELECT 'role_permission' AS source_table, 'role_permissions' AS target_table, count(*)::bigint AS expected_rows, (SELECT count(*)::bigint FROM public."role_permissions") AS actual_rows
FROM legacy_raw.role_permission rp
JOIN legacy_raw.roles r ON r.id = rp.role_id
JOIN legacy_raw.permissions p ON p.id = rp.permission_id
UNION ALL
SELECT 'tb_url_redirect' AS source_table, 'url_redirects' AS target_table, 1::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."url_redirects"
UNION ALL
SELECT 'users' AS source_table, 'users' AS target_table, 4::bigint AS expected_rows, count(*)::bigint AS actual_rows FROM public."users"
UNION ALL
SELECT 'user_role' AS source_table, 'user_roles' AS target_table, count(*)::bigint AS expected_rows, (SELECT count(*)::bigint FROM public."user_roles") AS actual_rows
FROM legacy_raw.user_role ur
JOIN legacy_raw.users u ON u.id = ur.user_id
JOIN legacy_raw.roles r ON r.id = ur.role_id
)
SELECT source_table,
       target_table,
       expected_rows,
       actual_rows,
       CASE WHEN expected_rows = actual_rows THEN 'OK' ELSE 'MISMATCH' END AS status
FROM canonical_counts
ORDER BY source_table, target_table;

SELECT source_table,
       target_table,
       count(*)::bigint AS mapped_rows
FROM legacy_raw.legacy_import_mappings
GROUP BY source_table, target_table
ORDER BY source_table, target_table;

SELECT source_table,
       target_table,
       reason,
       count(*)::bigint AS skipped_rows
FROM legacy_raw.legacy_import_skipped_rows
GROUP BY source_table, target_table, reason
ORDER BY source_table, target_table, reason;

SELECT 'menus' AS table_name,
       coalesce((SELECT max(id) FROM public.menus), 0)::bigint AS max_id,
       (SELECT last_value FROM public.menus_id_seq)::bigint AS sequence_last_value,
       CASE
         WHEN (SELECT count(*) FROM public.menus) = 0 THEN 'EMPTY'
         WHEN (SELECT last_value FROM public.menus_id_seq) >= (SELECT max(id) FROM public.menus) THEN 'OK'
         ELSE 'MISMATCH'
       END AS status
UNION ALL
SELECT 'career_content' AS table_name,
       coalesce((SELECT max(id) FROM public.career_content), 0)::bigint AS max_id,
       (SELECT last_value FROM public.career_content_id_seq)::bigint AS sequence_last_value,
       CASE
         WHEN (SELECT count(*) FROM public.career_content) = 0 THEN 'EMPTY'
         WHEN (SELECT last_value FROM public.career_content_id_seq) >= (SELECT max(id) FROM public.career_content) THEN 'OK'
         ELSE 'MISMATCH'
       END AS status;
