/**
 * Migrate menus data from MySQL (data_menus_lengkap.sql) to PostgreSQL
 * 
 * This script:
 * 1. ONLY deletes data from the "menus" table — no other tables are affected
 * 2. Inserts all menu data from the MySQL dump, mapped to PostgreSQL/Prisma schema
 * 3. Resets the autoincrement sequence to avoid ID conflicts
 * 
 * Usage: npx ts-node scripts/migrate-menus-from-mysql.ts
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function migrateMenus() {
  console.log('🔄 Starting menus migration from MySQL data...');
  console.log('⚠️  This will ONLY affect the "menus" table. All other tables are untouched.\n');

  // All menu data from data_menus_lengkap.sql, converted to PostgreSQL format
  const menuData = [
    { id: 1, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Home', translations: null, slug: null, url: '/', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 0, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 2, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'About', translations: {"id":{"title":"Tentang","slug":null,"description":null},"en":{"title":"About","slug":null,"description":null}}, slug: null, url: '#', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'mega' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 3, parentId: 2, sectionTitle: null, sectionOrder: 0, title: 'Corporate Information', translations: {"id":{"title":"Informasi Perseroan","slug":null,"description":null},"en":{"title":"Corporate Information","slug":null,"description":null}}, slug: null, url: '/about/corporate-information', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 0, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 4, parentId: 2, sectionTitle: null, sectionOrder: 0, title: 'Corporate Overview', translations: {"id":{"title":"Ikhtisar Perusahaan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/about/corporate-overview', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 5, parentId: 2, sectionTitle: null, sectionOrder: 0, title: 'Milestone', translations: null, slug: null, url: '/about/milestone', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 2, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 6, parentId: 2, sectionTitle: null, sectionOrder: 0, title: 'Group Structures', translations: {"id":{"title":"Struktur Grup","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/about/group-structures', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 3, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 7, parentId: 2, sectionTitle: null, sectionOrder: 0, title: 'Management', translations: {"id":{"title":"Manajemen","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/about/management', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 4, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 8, parentId: 2, sectionTitle: null, sectionOrder: 0, title: 'Awards', translations: {"id":{"title":"Penghargaan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/about/awards', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 5, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 9, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Business', translations: {"id":{"title":"Bisnis","slug":null,"description":null},"en":{"title":"Business","slug":null,"description":null}}, slug: null, url: '#', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'mega' as const, order: 2, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 10, parentId: 9, sectionTitle: null, sectionOrder: 0, title: 'Linknet Enterprise', translations: {"id":{"title":null,"slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/business/linknet-enterprise', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 0, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 11, parentId: 9, sectionTitle: null, sectionOrder: 0, title: 'Linknet Fiber', translations: null, slug: null, url: '/business/linknet-fiber', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 12, parentId: 9, sectionTitle: null, sectionOrder: 0, title: 'Linknet Media', translations: null, slug: null, url: '/business/linknet-media', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 2, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 13, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Corporate Governance', translations: {"id":{"title":"Tata Kelola","slug":null,"description":null},"en":{"title":"Corporate Governance","slug":null,"description":null}}, slug: null, url: '#', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'mega' as const, order: 3, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 14, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Structure', translations: {"id":{"title":"Struktur Tata Kelola Perusahaan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/structure', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:03:48Z') },
    { id: 15, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Principle', translations: {"id":{"title":"Prinsip Tata Kelola Perusahaan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/principle', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 2, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:04:11Z') },
    { id: 16, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Guidance', translations: {"id":{"title":"Panduan Tata Kelola Perusahaan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/guidance', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 3, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:04:28Z') },
    { id: 17, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Article of Association', translations: {"id":{"title":"Anggaran Dasar","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/association', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 4, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:05:30Z') },
    { id: 18, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Code of Conduct', translations: {"id":{"title":"Kode Etik","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/code-of-conduct', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 5, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:05:50Z') },
    { id: 19, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Certified for Standarization of Management System', translations: {"id":{"title":"Sertifikasi Standarisasi Sistem Manajemen","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/summary-of-standardization', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 6, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:06:09Z') },
    { id: 20, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Organization Structures', translations: {"id":{"title":"Struktur Organisasi","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/organization-structure', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 7, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:06:21Z') },
    { id: 22, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Board & Committee Charters', translations: {"id":{"title":"Piagam Dewan & Komite","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/board-committee-charters', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 9, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:06:56Z') },
    { id: 23, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Whistleblowing System', translations: {"id":{"title":"Sistem Whistleblowing","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/whistleblowing-system', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 10, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:07:14Z') },
    { id: 24, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Whistleblowing Policy', translations: {"id":{"title":"Kebijakan Whistleblowing","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/whistleblowing-policy', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 11, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:07:31Z') },
    { id: 25, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'Data Privacy Policy', translations: {"id":{"title":"Kebijakan Privasi Data","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/data-privacy-policy', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 12, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:07:50Z') },
    { id: 26, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Investor', translations: null, slug: null, url: '#', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'mega' as const, order: 4, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 27, parentId: 26, sectionTitle: null, sectionOrder: 1, title: 'GMS Announcement', translations: {"id":{"title":"Pengumuman RUPS","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor/gms-announcement', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 0, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 28, parentId: 26, sectionTitle: null, sectionOrder: 1, title: 'Emiten Announcement', translations: {"id":{"title":"Pengumuman Emiten","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor/emiten-announcement', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 2, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:09:13Z') },
    { id: 29, parentId: 26, sectionTitle: null, sectionOrder: 1, title: 'Public Expose Announcement', translations: {"id":{"title":"Pengumuman Paparan Publik","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor/public-expose-announcement', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 3, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:09:26Z') },
    { id: 30, parentId: 26, sectionTitle: null, sectionOrder: 1, title: 'Financial Statement', translations: {"id":{"title":"Laporan Keuangan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor/financial-statement', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 4, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:10:07Z') },
    { id: 31, parentId: 26, sectionTitle: null, sectionOrder: 1, title: 'Annual Report', translations: {"id":{"title":"Laporan Tahunan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor/annual-report', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 5, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:10:17Z') },
    { id: 32, parentId: 26, sectionTitle: null, sectionOrder: 1, title: 'Sustainability Report', translations: {"id":{"title":"Laporan Keberlanjutan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor/sustainable-report', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 6, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T09:07:11Z') },
    { id: 33, parentId: 26, sectionTitle: 'Investor', sectionOrder: 2, title: 'Stock Price', translations: {"id":{"title":"Harga Saham","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor-relations', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-11-26T07:08:55Z') },
    { id: 34, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Media', translations: null, slug: null, url: '/news', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 5, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 35, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Sustainability', translations: {"id":{"title":"Keberlanjutan","slug":null,"description":null},"en":{"title":"Sustainability","slug":null,"description":null}}, slug: null, url: '/sustainability', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 6, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 36, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Life at Linknet', translations: {"id":{"title":"Life at Linknet","slug":null,"description":null},"en":{"title":"Career","slug":null,"description":null}}, slug: null, url: '/life-at-linknet', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 7, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    // Footer menus
    { id: 37, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Company', translations: {"id":{"title":"Perusahaan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '#', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'dropdown' as const, order: 8, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 38, parentId: 37, sectionTitle: null, sectionOrder: 0, title: 'About', translations: {"id":{"title":"Tentang","slug":"/about/corporate-information","description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/about/corporate-overview', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 0, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 39, parentId: 37, sectionTitle: null, sectionOrder: 0, title: 'Management', translations: {"id":{"title":"Manajemen","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/about/management', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 40, parentId: 37, sectionTitle: null, sectionOrder: 0, title: 'Business', translations: {"id":{"title":"Bisnis","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/business/linknet-enterprise', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 2, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 41, parentId: 37, sectionTitle: null, sectionOrder: 0, title: 'Media & News', translations: {"id":{"title":null,"slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/news', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 3, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 42, parentId: 37, sectionTitle: null, sectionOrder: 0, title: 'Awards', translations: {"id":{"title":"Penghargaan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/about/awards', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 4, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 43, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Investor Relations', translations: null, slug: null, url: '#', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'dropdown' as const, order: 9, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 44, parentId: 43, sectionTitle: null, sectionOrder: 0, title: 'Stock Price', translations: {"id":{"title":"Harga Saham","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor-relations', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 0, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 45, parentId: 43, sectionTitle: null, sectionOrder: 0, title: 'GMS Announcements', translations: {"id":{"title":"Pengumuman RUPS","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor/gms-announcement', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 46, parentId: 43, sectionTitle: null, sectionOrder: 0, title: 'Reports', translations: {"id":{"title":"Laporan Keuangan","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/investor/financial-statement', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 2, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 47, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Join #FirstSquad', translations: null, slug: null, url: '#', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'dropdown' as const, order: 10, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 48, parentId: 47, sectionTitle: null, sectionOrder: 0, title: 'Life at Linknet', translations: null, slug: null, url: '/life-at-linknet', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 0, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 49, parentId: 47, sectionTitle: null, sectionOrder: 0, title: 'Explore Career', translations: {"id":{"title":"Karir","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/career', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 50, parentId: null, sectionTitle: null, sectionOrder: 0, title: 'Platform', translations: null, slug: null, url: '#', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'dropdown' as const, order: 11, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 51, parentId: 50, sectionTitle: null, sectionOrder: 0, title: 'Corporate Policy', translations: {"id":{"title":"Kebijakan Linknet","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/corporate-governance/linknet-policy', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 0, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 53, parentId: 50, sectionTitle: null, sectionOrder: 0, title: 'Contact Us', translations: {"id":{"title":"Hubungi Kami","slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: null, url: '/contact-us', icon: null, image: null, description: null, badge: null, position: 'footer' as const, type: 'link' as const, order: 1, isActive: true, openNewTab: false, cssClass: null, createdBy: 'system', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-10-21T08:47:16Z'), updatedAt: new Date('2025-12-19T08:15:52Z') },
    { id: 55, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'ABAC Policy', translations: {"id":{"title":null,"slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: 'corporate-governance/anti-bribery-and-corruption-policy', url: 'https://linknet.co.id/corporate-governance/anti-bribery-and-corruption-policy', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 13, isActive: true, openNewTab: false, cssClass: null, createdBy: 'admin@gmail.com', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-12-19T08:15:41Z'), updatedAt: new Date('2025-12-19T09:01:14Z') },
    { id: 56, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'GDS Policy', translations: {"id":{"title":null,"slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: 'corporate-governance/gifts-donations-sponsorships-policy', url: 'https://linknet.co.id/corporate-governance/gifts-donations-sponsorships-policy', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 15, isActive: true, openNewTab: false, cssClass: null, createdBy: 'admin@gmail.com', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-12-19T08:17:52Z'), updatedAt: new Date('2025-12-19T09:01:53Z') },
    { id: 58, parentId: 13, sectionTitle: null, sectionOrder: 0, title: 'ABAC Clause', translations: {"id":{"title":null,"slug":null,"description":null},"en":{"title":null,"slug":null,"description":null}}, slug: 'corporate-governance/anti-bribery-and-corruption-clause', url: 'https://linknet.co.id/corporate-governance/anti-bribery-and-corruption-clause', icon: null, image: null, description: null, badge: null, position: 'header' as const, type: 'link' as const, order: 14, isActive: true, openNewTab: false, cssClass: null, createdBy: 'admin@gmail.com', updatedBy: 'admin@gmail.com', createdAt: new Date('2025-12-19T09:02:52Z'), updatedAt: new Date('2025-12-19T09:13:10Z') },
  ];

  try {
    // Use transaction to ensure atomicity — if anything fails, nothing changes
    await prisma.$transaction(async (tx) => {
      // Step 1: Delete ALL children first (to avoid FK constraint), then parents
      console.log('🗑️  Deleting existing menu data (children first)...');
      await tx.menu.deleteMany({ where: { parentId: { not: null } } });
      await tx.menu.deleteMany({ where: { parentId: null } });
      console.log('   ✅ Existing menus cleared');

      // Step 2: Insert menus — parents first (parentId = null), then children
      console.log('📝 Inserting menu data...');
      
      const parents = menuData.filter(m => m.parentId === null);
      const children = menuData.filter(m => m.parentId !== null);

      // Insert parents
      for (const menu of parents) {
        await tx.$executeRawUnsafe(
          `INSERT INTO menus (id, parent_id, section_title, section_order, title, translations, slug, url, icon, image, description, badge, position, type, "order", is_active, open_new_tab, css_class, created_by, updated_by, created_at, updated_at)
           VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8, $9, $10, $11, $12, $13::"MenuPosition", $14::"MenuType", $15, $16, $17, $18, $19, $20, $21, $22)`,
          BigInt(menu.id), null, menu.sectionTitle, menu.sectionOrder, menu.title,
          menu.translations ? JSON.stringify(menu.translations) : null,
          menu.slug, menu.url, menu.icon, menu.image, menu.description, menu.badge,
          menu.position, menu.type, menu.order, menu.isActive, menu.openNewTab,
          menu.cssClass, menu.createdBy, menu.updatedBy, menu.createdAt, menu.updatedAt
        );
      }
      console.log(`   ✅ Inserted ${parents.length} parent menus`);

      // Insert children
      for (const menu of children) {
        await tx.$executeRawUnsafe(
          `INSERT INTO menus (id, parent_id, section_title, section_order, title, translations, slug, url, icon, image, description, badge, position, type, "order", is_active, open_new_tab, css_class, created_by, updated_by, created_at, updated_at)
           VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8, $9, $10, $11, $12, $13::"MenuPosition", $14::"MenuType", $15, $16, $17, $18, $19, $20, $21, $22)`,
          BigInt(menu.id), BigInt(menu.parentId!), menu.sectionTitle, menu.sectionOrder, menu.title,
          menu.translations ? JSON.stringify(menu.translations) : null,
          menu.slug, menu.url, menu.icon, menu.image, menu.description, menu.badge,
          menu.position, menu.type, menu.order, menu.isActive, menu.openNewTab,
          menu.cssClass, menu.createdBy, menu.updatedBy, menu.createdAt, menu.updatedAt
        );
      }
      console.log(`   ✅ Inserted ${children.length} child menus`);

      // Step 3: Reset sequence to max id + 1
      const maxId = Math.max(...menuData.map(m => m.id));
      await tx.$executeRawUnsafe(
        `SELECT setval(pg_get_serial_sequence('menus', 'id'), $1)`,
        BigInt(maxId)
      );
      console.log(`   ✅ Reset sequence to ${maxId}`);
    });

    // Verify
    const totalCount = await prisma.menu.count();
    const headerCount = await prisma.menu.count({ where: { position: 'HEADER' } });
    const footerCount = await prisma.menu.count({ where: { position: 'FOOTER' } });

    console.log('\n🎉 Migration completed successfully!');
    console.log(`📊 Summary:`);
    console.log(`   Total menus: ${totalCount}`);
    console.log(`   Header menus: ${headerCount}`);
    console.log(`   Footer menus: ${footerCount}`);
    console.log(`\n⚠️  No other tables were affected.`);

  } catch (error) {
    console.error('❌ Migration failed (transaction rolled back, no data changed):', error);
    throw error;
  }
}

migrateMenus()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
