trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  tag: 'web-$(Build.BuildId)'
  BuildConfiguration: 'Release'
  Uri: '329599622292.dkr.ecr.ap-southeast-3.amazonaws.com'
  RepositoryName: 'linknet/corporate-web'
  awsCredentials: 'aws-iam-system-azure-devops-holdco-dev-corporate'

steps:
- checkout: self

# Build Docker image
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: build
    Dockerfile: $(System.DefaultWorkingDirectory)/Dockerfile
    buildContext: $(System.DefaultWorkingDirectory)
    repository: $(Uri)/$(RepositoryName)
    tags: |
      $(tag)

# Push Docker image ke ECR AWS
- task: ECRPushImage@1
  displayName: 'Push Docker Image to AWS ECR'
  inputs:
    awsCredentials: $(awsCredentials)
    regionName: ap-southeast-3
    imageSource: 'imagename'
    sourceImageName: $(Uri)/$(RepositoryName)
    sourceImageTag: $(tag)
    pushTag: $(tag)
    repositoryName: $(RepositoryName)
    autoCreateRepository: true

- script: |
    echo $(tag)
    echo End of script.
  displayName: 'End of script'

# MSDO SCAN
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps Scan'
  condition: always()
  inputs:
    command: 'run'
    policy: 'azuredevops'
    tools: 'checkov, templateanalyzer'
    publish: true
    artifactName: 'CodeAnalysisLogs'

# PUBLISH ARTIFACTS
- task: PublishBuildArtifacts@1
  displayName: 'Publish Security Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'security-reports'