trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'
  Uri: '207567776092.dkr.ecr.ap-southeast-3.amazonaws.com'
  RepositoryName: 'onestreamcoid/onestream'
  awsCredentials: 'aws-iam-system-azure-devops-mediaco-ecr-dev-onestream'

steps:

# 1️⃣ SAST (Fail fast — paling awal)
- task: MicrosoftSecurityDevOps@1
  displayName: 'SAST Scan (ESLint)'
  inputs:
    command: 'run'
    policy: 'azuredevops'
    categories: 'code'
    languages: 'javascript'
    tools: 'eslint'
    break: true

# 2️⃣ Build Image
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    Dockerfile: $(System.DefaultWorkingDirectory)/Dockerfile
    buildContext: $(System.DefaultWorkingDirectory)
    repository: $(Uri)/$(RepositoryName)
    tags: |
      $(Build.BuildId)

# 3️⃣ Container Scan (scan image sebelum push)
- task: MicrosoftSecurityDevOps@1
  displayName: 'Container Scan (Trivy)'
  env:
    GDN_TRIVY_IMAGE: $(Uri)/$(RepositoryName):$(Build.BuildId)
  inputs:
    command: 'run'
    categories: 'artifacts'
    tools: 'trivy'
    break: true

# 4️⃣ Push ONLY if secure
- task: ECRPushImage@1
  inputs:
    awsCredentials: $(awsCredentials)
    regionName: ap-southeast-3
    imageSource: 'imagename'
    sourceImageName: $(Uri)/$(RepositoryName)
    sourceImageTag: $(Build.BuildId)
    pushTag: $(Build.BuildId)
    repositoryName: $(RepositoryName)
